### ISSUE TITLE
Do you plan to release an angular 7 compatible plugin ?

### ISSUE THREAD

**Issue by azherf** [MatthewLarner/cross-domain-storage#13]

**Comment by MatthewLarner** [comment]
Hi there, is there some special compatibility or format you need?

I've used this with React and a couple of other libraries, but no special wrapper should be needed.

If you can run Javascript somewhere that can safely run side effects then that's all you need.

In React, we run the functions in `ComponentDidMount` for example.

Hope that helps

**Comment by azherf** [comment]
Hi @MatthewLarner,
That is good to know. Can you point me to the type definition file for this plugin somewhere that I can use in my angular project ?

Thanks,
Azher
