### ISSUE TITLE
quotes on localStorage item values when sets

### ISSUE THREAD

**Issue by critot** [MatthewLarner/cross-domain-storage#17]
Hi,
I've this problem: when I create a guest and set an item in it (Angular6 app)

let p='aaa';
var createGuest = require('cross-domain-storage/guest');
var tStorage = createGuest('https://xyz');
tStorage.set('p', p), function (error, value) {
    console.log('Guest callback: ', error, value);
};

the result is that in guest local storage I've this item value
"aaa" (with quotes)

I think this is due to this piece of code in method.js:

set: function (event, data) {
window.localStorage.setItem(data.key, **JSON.stringify**(data.value));
...
}

thank you for your work

**Comment by MatthewLarner** [comment]
Should be resolved with https://github.com/MatthewLarner/cross-domain-storage/releases/tag/v2.0.0, we've just removed all data handling so strings should work as expected now.
