### ISSUE TITLE
It doesn't get a storage, if it is a string.

### ISSUE THREAD

**Issue by stelasido** [MatthewLarner/cross-domain-storage#18]
I don't know what is the problem (I guess, everything in the local storage is a string), but if I use this value `bar` - `bazStorage.get('test', function(error, value) `, returns `null` for it and the error is `undefined`.

If I use a number (for the example 45 or 56565656777) in the local storage value, it works fine.

**Comment by ShivamBhardwaj007** [comment]
> I don't know what is the problem (I guess, everything in the local storage is a string), but if I use this value `bar` - `bazStorage.get('test', function(error, value) `, returns `null` for it and the error is `undefined`.
> 
> If I use a number (for the example 45 or 56565656777) in the local storage value, it works fine.

face same issue any suggestion  for me

**Comment by ShivamBhardwaj007** [comment]
Set and get Not working.but in my browser i can see the host local storage value but i can not able to access in my code.


const createStorageGuest = require('cross-domain-storage/guest');
    const storageGuest = createStorageGuest('http://localhost:4200/accessStorage');
    this.resultData = storageGuest.get('foo', function (data: any) {
      console.log('Guest callback: ', data);
    });
    storageGuest.set('foo', 'bar', function(error, data) {
      // foo is now set to 'bar'
  });
    console.log('storage value' + this.resultData);

**Comment by MatthewLarner** [comment]
Should be resolved with https://github.com/MatthewLarner/cross-domain-storage/releases/tag/v2.0.0, we've just removed all data handling so strings should work as expected now.
