### ISSUE TITLE
Can I update the local storage for a domain associated with webpage loaded in an iframe?

### ISSUE THREAD

**Issue by TCourtneyOwen** [MatthewLarner/cross-domain-storage#31]
If I have index.html running on localhost that loads for example https://www.washingtonpost.com/ in an iframe, can I use this package to set key/value pairs for the local storage of https://www.washingtonpost.com/?  

I have been looking for a way to modify the local storage of a 3rd party domain that I load in an iframe and wonder if this possible and if this package might work for me

Thanks,

Courtney

**Comment by MatthewLarner** [comment]
Hi Courtney, 

This package is not going to help you I think.

Its use cases are restricted to sites that you control and want to allow getting and setting local storage items.

So for your example if you were in control of https://www.washingtonpost.com/ then you could set up a `host` with this package, set the domains you want to allow access to, and then use the `guest` component on the other sites to set / get.
