### ISSUE TITLE
iFrame visible

### ISSUE THREAD

**Issue by colindotfun** [MatthewLarner/cross-domain-storage#36]
Should the iFrame not be invisible? 

Seems to be visible on Chrome/Safari, etc.

![image](https://user-images.githubusercontent.com/21294951/90627768-561a2a00-e214-11ea-8c6a-6777afd1e7e9.png)

**Comment by colindotfun** [comment]
Realized you can just close the connection to close the iFrame.

**Comment by MatthewLarner** [comment]
Thanks @colinricardo, actually this was a bug introduced in 2.0.6.

Fixed here #37 and published in 2.0.7
